cuda_graph_config:
    enable_padding: true
    max_batch_size: 128
enable_attention_dp: false
print_iter_log: true
kv_cache_config:
    dtype: fp8
    free_gpu_memory_fraction: 0.8
    enable_block_reuse: false
stream_interval: 10
moe_config:
    backend: TRTLLM
batch_wait_timeout_iters: 40
batch_wait_max_tokens_ratio: 0.8
torch_compile_config:
    capture_num_tokens: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 768, 1024, 1280, 1536, 1792, 2048, 2304, 2560, 2816, 3072, 3328, 3584, 3840, 4096, 4352, 4608, 4864, 5120, 5376, 5632, 5888, 6144, 6400, 6656, 6912, 7168, 7424, 7680, 7936, 8192]
    enable_piecewise_cuda_graph: true
